[workspace]
members = ["lib/*"]
package.version = "0.1.0"
package.edition = "2024"

[package]
name = "gc-analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
good_lp = { version = "1.14.0", features = [
    "clarabel",
], default-features = false }
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
